chore: update bashrc

diff --git a/home/bashrc b/home/bashrc
--- a/home/bashrc
+++ b/home/bashrc
@@ -1,45 +1,147 @@
-#---------------------------------------------------------------------------
-# Prompt
-#---------------------------------------------------------------------------
-RED="\033[0;31m"
-BROWN="\033[0;33m"
-GREY="\033[0;97m"
-GREEN="\033[0;32m"
-BLUE="\033[0;34m"
-PS_CLEAR="\033[0m"
-SCREEN_ESC="\033k\033\134"
+#!/usr/bin/env bash
 
-COLOR1="${BLUE}"
-COLOR2="${BLUE}"
-P="\$"
+# If not running interactively, don't do anything
+[[ -n $PS1 ]] || return
 
-prompt_simple() {
-    unset PROMPT_COMMAND
-    PS1="\W\$(parse_git_branch) → "
-    PS2="> "
+export EDITOR=vim
+export GREP_COLOR='1;36'
+export LSCOLORS='ExGxbEaECxxEhEhBaDaCaD'
+export PAGER='less'
+
+source <(fzf --bash)
+
+# History
+HISTFILE="$HOME/.bash_history"
+HISTSIZE=10000000
+SAVEHIST=10000000
+
+# Support colors in less
+export LESS_TERMCAP_mb=$(tput bold; tput setaf 1)
+export LESS_TERMCAP_md=$(tput bold; tput setaf 1)
+export LESS_TERMCAP_me=$(tput sgr0)
+export LESS_TERMCAP_se=$(tput sgr0)
+export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4)
+export LESS_TERMCAP_ue=$(tput sgr0)
+export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 2)
+export LESS_TERMCAP_mr=$(tput rev)
+export LESS_TERMCAP_mh=$(tput dim)
+export LESS_TERMCAP_ZN=$(tput ssubm)
+export LESS_TERMCAP_ZV=$(tput rsubm)
+export LESS_TERMCAP_ZO=$(tput ssupm)
+export LESS_TERMCAP_ZW=$(tput rsupm)
+
+alias lg=lazygit
+
+# Enable color support of ls
+if ls --color=auto &>/dev/null; then
+        alias ls='ls -p --color=auto'
+else
+        alias ls='ls -p -G'
+fi
+
+# print a colorized diff
+colordiff() {
+        local red=$(tput setaf 1 2>/dev/null)
+        local green=$(tput setaf 2 2>/dev/null)
+        local cyan=$(tput setaf 6 2>/dev/null)
+        local reset=$(tput sgr0 2>/dev/null)
+
+        diff -u "$@" | awk "
+        /^\-/ {
+                printf(\"%s\", \"$red\");
+        }
+        /^\+/ {
+                printf(\"%s\", \"$green\");
+        }
+        /^@/ {
+                printf(\"%s\", \"$cyan\");
+        }
+
+        {
+                print \$0 \"$reset\";
+        }"
+
+        return "${PIPESTATUS[0]}"
 }
 
-prompt_compact() {
-    unset PROMPT_COMMAND
-    PS1="${COLOR1}${P}${PS_CLEAR} "
-    PS2="> "
+# Print all 256 colors
+colors() {
+        local i
+        for i in {0..255}; do
+                printf "\x1b[38;5;${i}mcolor %d\n" "$i"
+        done
+        tput sgr0
 }
 
-prompt_color() {
-    PS1="${GREEN}\W\$(parse_git_branch) → ${GREY}"
-    PS2="\033[33;1mcontinue \033[0m\033[1m> "
+# Change the prompt colors to a theme, themes are 0-29
+set_prompt_colors() {
+        local h=${1:-0}
+        local color=
+        local i=0
+        local j=0
+        for i in {22..231}; do
+                ((i % 30 == h)) || continue
+
+                color=${COLOR256[$i]}
+                # cache the tput colors
+                if [[ -z $color ]]; then
+                        COLOR256[$i]=$(tput setaf "$i")
+                        color=${COLOR256[$i]}
+                fi
+                PROMPT_COLORS[$j]=$color
+                ((j++))
+        done
 }
 
-parse_git_branch() {
-    [ -d .git ] || return 1
-    git symbolic-ref HEAD 2> /dev/null | sed 's#\(.*\)\/\([^\/]*\)$# \2#'
+# Construct the prompt
+# [(exit code)] <user> - <hostname> <uname> <cwd> [git branch] <$|#>
+
+# exit code of last process
+PS1='$(ret=$?;(($ret!=0)) && echo "\[${COLOR256[0]}\]($ret) \[${COLOR256[256]}\]")'
+
+# username (red for root)
+PS1+='\[${PROMPT_COLORS[0]}\]\[${COLOR256[257]}\]$(((UID==0)) && echo "\[${COLOR256[0]}\]")\u\[${COLOR256[256]}\]@'
+
+# zonename (global zone warning)
+PS1+='\[${COLOR256[0]}\]\[${COLOR256[257]}\]'"$(zonename 2>/dev/null | grep -q '^global$' && echo 'GZ:')"'\[${COLOR256[256]}\]'
+
+# hostname
+PS1+='\[${PROMPT_COLORS[3]}\]\H '
+
+# PID
+PS1+='\[${PROMPT_COLORS[4]}\](PID:$$) \[${COLOR256[256]}\]'
+
+# uname
+PS1+='\[${PROMPT_COLORS[2]}\]'"$(uname | tr '[:upper:]' '[:lower:]')"' '
+
+# cwd
+PS1+='\[${PROMPT_COLORS[5]}\]\w '
+
+# optional git branch
+PS1+='$(branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null); [[ -n $branch ]] && echo "\[${PROMPT_COLORS[2]}\](\[${PROMPT_COLORS[3]}\]git:$branch\[${PROMPT_COLORS[2]}\]) ")'
+
+# prompt character
+PS1+='\[${PROMPT_COLORS[0]}\]\$\[${COLOR256[256]}\] '
+
+# set the theme
+set_prompt_colors 24
+
+# Prompt command
+_prompt_command() {
+        local user=$USER
+        local host=${HOSTNAME%%.*}
+        local pwd=${PWD/#$HOME/\~}
+        local ssh=
+        [[ -n $SSH_CLIENT ]] && ssh='[ssh] '
+        printf "\033]0;%s%s@%s:%s\007" "$ssh" "$user" "$host" "$pwd"
 }
+PROMPT_COMMAND=_prompt_command
 
-# Set default prompt if interactive
-test -n "$PS1" &&
-prompt_color
+PROMPT_DIRTRIM=6
 
-# Ghostty setup. For testing.
-# if [ -n "$GHOSTTY_RESOURCES_DIR" ]; then
-#     builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/bash/ghostty.bash"
-# fi
+# load completion
+. /etc/bash/bash_completion 2>/dev/null ||
+        . ~/.bash_completion 2>/dev/null
+
+
+eval "$(zoxide init --cmd cd bash)"
